import { useEffect, useMemo, useState, type FormEvent } from 'react'
import type { Session } from '@supabase/supabase-js'
import { databaseConfigured, supabase } from './supabaseClient'
import './portal.css'
import './portal-config.css'

type Membership = { tenant_id: string; role: string; tenants: { name: string; minimum_reporting_group: number } | null }
type Report = { id: string; period_start: string; period_end: string; received_at: string; minimum_group_applied: number; privacy_gateway_version: string }
type Metric = { metric: string; dimension: string; count_value: number | null; numeric_value: number | null; currency: string | null }
type Enquiry = { id: string; name: string; work_email: string; company: string; role_title: string | null; message: string; status: string; created_at: string }
type ProductConfiguration = { tenant_id:string; product_name:string; brand_primary:string; enabled_features:string[]; anonymous_vibe_delay_minutes:number; maximum_vibes_per_sailing_day:number; maximum_vconnect_requests_per_sailing_day:number; maximum_feedback_questions:number; minimum_reporting_group:number; vconnect_request_options:string[]; vconnect_venue_options:string[]; vconnect_time_options:string[]; vibe_retention_days:number; vconnect_retention_days:number; release_channel:'stable'|'pilot'|'paused' }
const productFeatures=['interests','meetups','vibes','vconnect','crew-recognition','event-feedback','notifications','commerce']
const labels: Record<string, string> = { activated_guests:'Activated guests', passenger_vibes:'Passenger vibes', crew_recognitions:'Crew recognitions', event_feedback_responses:'Live feedback', issues_resolved:'Issues resolved', commerce_confirmed:'Confirmed bookings', attributed_net_value:'Attributed net value', social_shares:'Passenger-led shares' }
const parseOptions=(value:string)=>[...new Set(value.split(',').map(item=>item.trim().toLowerCase()).filter(Boolean))]

function ConfigurationPanel({value,onChange,onSave,saving,notice}:{value:ProductConfiguration;onChange:(value:ProductConfiguration)=>void;onSave:()=>void;saving:boolean;notice:string}){
  const number=(key:keyof ProductConfiguration,next:string)=>onChange({...value,[key]:Number(next)})
  const options=(key:'vconnect_request_options'|'vconnect_venue_options'|'vconnect_time_options',next:string)=>onChange({...value,[key]:parseOptions(next)})
  return <section className="portal-panel"><h2>Product and operator-edge configuration</h2><p className="portal-empty">White-label, safety, retention, prepared VConnect options and controlled release settings. Person-level blocks and reports remain inside the operator edge.</p><div className="portal-config">
    <label>Product name<input value={value.product_name} onChange={event=>onChange({...value,product_name:event.target.value})}/></label>
    <label>Brand colour<input type="color" value={value.brand_primary} onChange={event=>onChange({...value,brand_primary:event.target.value})}/></label>
    <label>Release channel<select value={value.release_channel} onChange={event=>onChange({...value,release_channel:event.target.value as ProductConfiguration['release_channel']})}><option value="stable">Stable</option><option value="pilot">Pilot</option><option value="paused">Paused</option></select></label>
    <label>Vibe delay (minutes)<input type="number" min="0" max="1440" value={value.anonymous_vibe_delay_minutes} onChange={event=>number('anonymous_vibe_delay_minutes',event.target.value)}/></label>
    <label>Vibes per sailing day<input type="number" min="1" max="5" value={value.maximum_vibes_per_sailing_day} onChange={event=>number('maximum_vibes_per_sailing_day',event.target.value)}/></label>
    <label>VConnect requests/day<input type="number" min="1" max="1" value={value.maximum_vconnect_requests_per_sailing_day} onChange={event=>number('maximum_vconnect_requests_per_sailing_day',event.target.value)}/></label>
    <label>Vibe retention (days)<input type="number" min="1" max="30" value={value.vibe_retention_days} onChange={event=>number('vibe_retention_days',event.target.value)}/></label>
    <label>VConnect retention (days)<input type="number" min="1" max="90" value={value.vconnect_retention_days} onChange={event=>number('vconnect_retention_days',event.target.value)}/></label>
    <label>Feedback questions<input type="number" min="1" max="5" value={value.maximum_feedback_questions} onChange={event=>number('maximum_feedback_questions',event.target.value)}/></label>
    <label className="portal-config-wide">Prepared request IDs<input value={value.vconnect_request_options.join(', ')} onChange={event=>options('vconnect_request_options',event.target.value)}/></label>
    <label className="portal-config-wide">Approved public venue IDs<input value={value.vconnect_venue_options.join(', ')} onChange={event=>options('vconnect_venue_options',event.target.value)}/></label>
    <label className="portal-config-wide">Prepared time IDs<input value={value.vconnect_time_options.join(', ')} onChange={event=>options('vconnect_time_options',event.target.value)}/></label>
  </div><div className="portal-feature-grid">{productFeatures.map(feature=><label key={feature}><input type="checkbox" checked={value.enabled_features.includes(feature)} onChange={event=>onChange({...value,enabled_features:event.target.checked?[...value.enabled_features,feature]:value.enabled_features.filter(item=>item!==feature)})}/><span>{feature}</span></label>)}</div><button onClick={onSave} disabled={saving}>{saving?'Saving…':'Save controlled configuration'}</button>{notice&&<p className="portal-status">{notice}</p>}</section>
}

export default function Portal() {
  const [session,setSession]=useState<Session|null>(null), [email,setEmail]=useState(''), [notice,setNotice]=useState(''), [error,setError]=useState('')
  const [memberships,setMemberships]=useState<Membership[]>([]), [reports,setReports]=useState<Report[]>([]), [metrics,setMetrics]=useState<Metric[]>([]), [enquiries,setEnquiries]=useState<Enquiry[]>([])
  const [configuration,setConfiguration]=useState<ProductConfiguration|null>(null),[saving,setSaving]=useState(false)
  useEffect(()=>{ if(!supabase)return; supabase.auth.getSession().then(({data})=>setSession(data.session)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>data.subscription.unsubscribe() },[])
  useEffect(()=>{ if(!supabase||!session)return; void (async()=>{
    setError('')
    const m=await supabase.from('memberships').select('tenant_id,role,tenants(name,minimum_reporting_group)')
    if(m.error){setError('Your account has not been assigned to an operator workspace.');return}
    const rows=(m.data||[]) as unknown as Membership[]; setMemberships(rows)
    if(rows[0]){const c=await supabase.from('tenant_product_configuration').select('tenant_id,product_name,brand_primary,enabled_features,anonymous_vibe_delay_minutes,maximum_vibes_per_sailing_day,maximum_vconnect_requests_per_sailing_day,maximum_feedback_questions,minimum_reporting_group,vconnect_request_options,vconnect_venue_options,vconnect_time_options,vibe_retention_days,vconnect_retention_days,release_channel').eq('tenant_id',rows[0].tenant_id).maybeSingle();setConfiguration((c.data as ProductConfiguration|null)||{tenant_id:rows[0].tenant_id,product_name:'CruiseConnect',brand_primary:'#173f47',enabled_features:productFeatures,anonymous_vibe_delay_minutes:60,maximum_vibes_per_sailing_day:5,maximum_vconnect_requests_per_sailing_day:1,maximum_feedback_questions:3,minimum_reporting_group:rows[0].tenants?.minimum_reporting_group||20,vconnect_request_options:['coffee-in-atrium','join-trivia','before-show'],vconnect_venue_options:['atrium-cafe','trivia-lounge','theatre-entrance','promenade'],vconnect_time_options:['today-afternoon','today-evening','tomorrow-morning','tomorrow-afternoon'],vibe_retention_days:14,vconnect_retention_days:30,release_channel:'stable'})}
    const r=await supabase.from('aggregate_reports').select('id,period_start,period_end,received_at,minimum_group_applied,privacy_gateway_version').order('period_end',{ascending:false}).limit(24)
    const reportRows=(r.data||[]) as Report[]; setReports(reportRows)
    if(reportRows.length){const x=await supabase.from('aggregate_metrics').select('metric,dimension,count_value,numeric_value,currency').eq('report_id',reportRows[0].id);setMetrics((x.data||[]) as Metric[])}
    if(rows.some(v=>v.role==='tisonik_admin')){const q=await supabase.from('pilot_requests').select('id,name,work_email,company,role_title,message,status,created_at').order('created_at',{ascending:false}).limit(100);setEnquiries((q.data||[]) as Enquiry[])}
  })() },[session])
  const totals=useMemo(()=>metrics.reduce<Record<string,{value:number,currency?:string}>>((a,m)=>{if(m.dimension==='overall'){a[m.metric]={value:(a[m.metric]?.value||0)+Number(m.numeric_value??m.count_value??0),currency:m.currency||a[m.metric]?.currency}}return a},{}),[metrics])
  const signIn=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setNotice('Sending secure link…');const {error:e2}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/portal/`}});setNotice(e2?'Unable to send. Contact the site administrator.':'Check your inbox for the secure sign-in link.')}
  const saveConfiguration=async()=>{if(!supabase||!configuration)return;setSaving(true);setError('');const {error:e2}=await supabase.from('tenant_product_configuration').upsert({...configuration,updated_at:new Date().toISOString()},{onConflict:'tenant_id'});setSaving(false);setNotice(e2?'Configuration could not be saved.':'Product configuration saved.');if(e2)setError(e2.message)}
  if(!databaseConfigured)return <main className="portal-shell"><section className="portal-login"><h1>Portal configuration is being completed.</h1><p>No operational data is exposed.</p></section></main>
  if(!session)return <main className="portal-shell"><section className="portal-login"><a href="/" className="portal-brand">Tisonik</a><p className="portal-kicker">SECURE OPERATIONS PORTAL</p><h1>Sign in to your authorised workspace.</h1><p>Use the work email invited by Tisonik or your cruise-line administrator. Passenger data is not held here.</p><form onSubmit={signIn}><label>Work email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@cruiseline.com"/></label><button>Email me a secure link</button></form>{notice&&<p className="portal-status" role="status">{notice}</p>}</section></main>
  const admin=memberships.some(v=>v.role==='tisonik_admin')
  return <main className="portal-shell portal-authenticated"><header><div><a href="/" className="portal-brand">Tisonik</a><span>Aggregate operations portal</span></div><div><span>{session.user.email}</span><button onClick={()=>supabase?.auth.signOut()}>Sign out</button></div></header>
    <section className="portal-heading"><p className="portal-kicker">PRIVACY-SAFE PERFORMANCE</p><h1>{memberships[0]?.tenants?.name||'Authorised workspace'}</h1><p>Only thresholded aggregate KPIs and non-identifying health data are available. Passenger and crew source records remain with the cruise operator.</p></section>{error&&<p className="portal-error">{error}</p>}
    <section className="portal-kpis">{Object.entries(labels).map(([k,l])=><article key={k}><span>{l}</span><strong>{totals[k]?`${totals[k].currency||''}${totals[k].value.toLocaleString()}`:'—'}</strong><small>{reports.length?`Latest accepted period · ${reports[0].period_end}`:'Awaiting first report'}</small></article>)}</section>
    <section className="portal-panel"><h2>Accepted privacy-gateway reports</h2>{reports.length?<div className="portal-table"><div><b>Period</b><b>Threshold</b><b>Gateway</b><b>Received</b></div>{reports.map(r=><div key={r.id}><span>{r.period_start} → {r.period_end}</span><span>≥ {r.minimum_group_applied}</span><span>{r.privacy_gateway_version}</span><span>{new Date(r.received_at).toLocaleDateString()}</span></div>)}</div>:<p className="portal-empty">No reports received. This is an empty production workspace—not demo data.</p>}</section>
    {configuration&&memberships.some(v=>v.role==='tisonik_admin'||v.role==='operator_admin')&&<ConfigurationPanel value={configuration} onChange={setConfiguration} onSave={saveConfiguration} saving={saving} notice={notice}/>}
    {admin&&<section className="portal-panel"><h2>Pilot enquiries</h2>{enquiries.length?<div className="portal-requests">{enquiries.map(q=><article key={q.id}><div><strong>{q.company}</strong><span>{q.status}</span></div><p>{q.name}{q.role_title?` · ${q.role_title}`:''} · <a href={`mailto:${q.work_email}`}>{q.work_email}</a></p><blockquote>{q.message}</blockquote><small>{new Date(q.created_at).toLocaleString()}</small></article>)}</div>:<p className="portal-empty">No pilot enquiries yet.</p>}</section>}
  </main>
}
